### ISSUE TITLE
Change lineHighlight color

### ISSUE THREAD

**Issue by Gryzvwald** [Septh/vscode-wow-bundle#1]
Is it possible to add changing the lineHighlight color for any of the color themes? I'mnot a fan of the box outline and would prefer a solid color. Thank you.

**Comment by Septh** [comment]
I'm not sure I'm willing to do this. In my opinion, my themes ought to be direct replacements for VS Code's default themes, just handling extra syntactical scopes.

I'm leaving this question open for additional comments, though.

**Comment by Gryzvwald** [comment]
Completely understand that. Is there a way to add that in on a personal level? I'm not as familiar with the JSON syntax as the THTheme files.
