### ISSUE TITLE
Been using this for a while, but really would like some improvments

### ISSUE THREAD

**Issue by ghost** [Septh/vscode-wow-bundle#10]
The progress on this extension seem to be somewhat lacking as of late for whatever reason. I know life gets busy and people get bored etc... but I've been using it exlusivly (althought probably not in the best ways) for developing my own addon.

If help is wanted I would be more than willing to give it a shot. Although I don't have my extension experience I do learn pretty quck, especially if I'm pushed in the right direction with decent doumention and by setting up some goals. 

I'f you need any help getting a few more of those lacking feaures being working on I'd be happy to look into them as I would make my life easier in the long run.

Hit me up if you're interested. Maybe I could start somewhere small just t get an idea how everything is working and use other extensions to bring in some of the features you'll looking for by using them as a reference.

Thanks and keep up the good work!

**Comment by Septh** [comment]
Thank you very much. An update for BFA is on its way. I know I'm very late on this one, but I hope to release it next week.
