### ISSUE TITLE
Update for 8.1.5 from BlizzardInterfaceResources

### ISSUE THREAD

**Issue by Ketho** [Septh/vscode-wow-bundle#12]
I'm maintaining a list of API, widgets and events for 8.1.5
https://github.com/Ketho/BlizzardInterfaceResources

Is there way you could update the resources with this list or should I make a pull request? But to be honest, I'm not familiar with the workings of vscode extensions.

**Comment by Septh** [comment]
Wow! (no pun intended) Impressive work that will most certainly be very, very useful.

TBH, I didn't give WoW-Bundle all the attention it deserves lately. I'm not sure when I'll be able to pack a new version, but I'll do. Some time.

Thanks!

**Comment by JanGalek** [comment]
There is 9.01 :partying_face:

**Comment by leo-unglaub** [comment]
9.2.5 :)
