### ISSUE TITLE
Problem with invalid API

### ISSUE THREAD

**Issue by Stanzilla** [Septh/vscode-wow-bundle#4]
It seems like the detection of invalid ignores the fact that I have reassigned them and still colors them as invalid, is there any way to disable invalid coloring? 

For example I use `local tinsert = table.insert` all the time because I'm so used to the shorter version and it works fine but it is always flagged as invalid with your extension.

**Comment by Septh** [comment]
I knew this issue would surface one day :) 

There is no way the extension can make a difference between deprecated identifiers and valid, local reassignments like the one you are doing (colorization has no context, when the parser matches an identifier it doesn't know if that identifier was already met before). Also, there is no way to dynamically disable one rule in VSCode's colorizer.

The alternative here would be to either :
- entirely remove the `tinsert` identifier from the list of deprecated words, or
- change the color/style for these words to be less eye-catchy, eg. same color but bold or underlined.

What do you think? I'm open to suggestions.

**Comment by Stanzilla** [comment]
Hrm, not sure. I actually think that such a feature does not belong in a theme but your project is a bundle..so.. I don't really know. Deprecated API is usually handled by a linter.
