### ISSUE TITLE
Question about coloring inside tables

### ISSUE THREAD

**Issue by Stanzilla** [Septh/vscode-wow-bundle#5]
![code_2017-04-07_04-51-26](https://cloud.githubusercontent.com/assets/75278/24783666/fc3340ac-1b4d-11e7-879e-328d44395541.png)

so this table here, I don't quite understand the coloring here. `sort` is probably just different because it's a keyword but the different string colors? Please enlighten me :)

**Comment by Septh** [comment]
Some strings have a special meaning in Lua and in the WoW API and are colorized accordingly. For instance, the string `"CENTER"` may be used as a parameter to the `SetPoint()` function.

Currently, WoW Bundle recognizes and colorizes the following strings:
- Global event names like `"PLAYER_ENTERING_WORD"`, `"VARIABLES_LOADED"`, etc.
- Widgets script handlers like `"OnLoad"`, `"OnEnter"`, etc.
- A bunch of special parameters to most API functions like `SetPoint()` (e.g. `"CENTER"`, `"ANCHOR_LEFT"`, etc.), `SetFrameStrata()` (e.g. `"BACKGROUND"`, `"HIGH"`, etc.)
- A bunch of special parameters to some Lua functions like `type()` (e.g. `"number"`, `"nil"`, etc.), `__mode` (e.g. `"kv"`, etc.)

Also, please note that WoW Bundle features 3 special themes that help with colorizing anything WoW-related. For instance, your code would look like this with the theme named `Dark+ (WoW)`:

![dark wow](https://cloud.githubusercontent.com/assets/11949623/24853976/05ca4bb0-1ddd-11e7-801c-c21c7ecabb6e.png)

See the description in README.md for more info.
