### ISSUE TITLE
Support for 8.0+?

### ISSUE THREAD

**Issue by pretoast** [Septh/vscode-wow-bundle#9]
So, 8.0 just came out and I was wondering if there were plans on updating this extension anytime soon.

I'd love to help work on it, but I'm not very familiar with extension development.
If there is anything I can do to help, I'd love to.... but with my lack of knowledge I'd need at least a starting point. 

Thanks again for this great extension!

**Comment by Septh** [comment]
Yeah, I'll definitely update the bundle, though I can't really foresee when this will happen. "Anytime soon" seems a good time. :)
